name: mopen_test
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  meta: ^1.12.0
  equatable: ^2.0.5
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  isar_generator: ^3.1.0+1
  path_provider: ^2.1.3
  connectivity_plus: ^6.0.3
  intl: ^0.19.0
  flutter_localization: ^0.2.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.10

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/fonts/
  - assets/icons/
  - lib/l10n/app_en.arb
  - lib/l10n/app_uk.arb
  fonts:
    - family: Mariupol
      fonts:
        - asset: assets/fonts/Mariupol-Regular.otf
        - asset: assets/fonts/Mariupol-Bold.otf
        - asset: assets/fonts/Mariupol-Medium.otf